---
all:
  children:
    consul_servers:
       hosts:
         consul1:
           ansible_host: "192.168.56.201"
           ansible_private_key_file: ".vagrant/machines/consul1/virtualbox/private_key"
         consul2:
           ansible_host: "192.168.56.202"
           ansible_private_key_file: ".vagrant/machines/consul2/virtualbox/private_key"        
         consul3:
           ansible_host: "192.168.56.203"
           ansible_private_key_file: ".vagrant/machines/consul3/virtualbox/private_key"      
    nginx_servers:
      hosts:
        nginx1:
          ansible_host: "192.168.56.204"
          ansible_private_key_file: ".vagrant/machines/nginx1/virtualbox/private_key"
        nginx2:
          ansible_host: "192.168.56.205"
          ansible_private_key_file: ".vagrant/machines/nginx2/virtualbox/private_key"
    wp_servers:
      hosts:
        wp1:
          ansible_host: "192.168.56.206"
          ansible_private_key_file: ".vagrant/machines/wp1/virtualbox/private_key"  
        wp2:
          ansible_host: "192.168.56.207"
          ansible_private_key_file: ".vagrant/machines/wp2/virtualbox/private_key" 
    proxys:
      hosts:
        haproxy:
          ansible_host: "192.168.56.208"
          ansible_private_key_file: ".vagrant/machines/haproxy/virtualbox/private_key"            
...
